name: Download Git Repo to Self-Hosted Runner

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  download_repo:
    runs-on: self-hosted # This ensures the job runs on your self-hosted runner

    steps:
    # Step 1: Checkout the code from your GitHub repository
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Step 2: (Optional) Perform any actions on the repo
    - name: Run some command (e.g., build or test)
      run: |
        # You can add any build or test commands here
        echo "The repo has been downloaded successfully!"
        ls -la  # Example command to list the files in the repo

# Step 2: Build the Docker Image
    - name: Build Docker Image
      run: |
          docker build -t web-app:latest .

# Step 3: Run the Docker Container
    - name: Run Docker Container
      run: |
          docker run -d --name web-app-container -p 8080:80 web-app:latest
          echo "Application is running at http://localhost:8080"

# Step 4: Verify Container is Running
    - name: Check Docker Container Status
      run: |
          docker ps | grep web-app-container

